---
title: "AMR genes in Tanania humans"
output: html_notebook
---
# AMR genes in Tanania humans

### Content

-   
-   

### load libraries and set working dir

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggExtra)

wd <- "/Users/maloj/OneDrive - Danmarks Tekniske Universitet/HPC/ARG_flankophile"
```

### load data

```{r}
gene_variants <- read.table(paste0(wd, "/1_hits_all.tsv"), header = T, sep = "\t")
```

### look at data
```{r}

# how many variants of each gene
variant_summary <- gene_variants %>%
  group_by(GENE) %>%
  summarise(
    n_variants = n_distinct(VARIANT),
    n_observations = n()  # antal rækker per gen
  ) %>%
  filter(n_observations > 1) %>%  
  arrange(desc(n_variants))


ggplot(variant_summary, aes(x = n_observations, y = n_variants)) +
  geom_point(size = 4) +
  labs(
    title = "Number of Variants vs. Number of Observations per Gene",
    x = "Number of Observations",
    y = "Number of Unique Variants"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))


```
### genes with more than 10 observations
```{r}
#identify genes in at least ten samples
genes_10 <- variant_summary %>%
  filter(n_observations >= 10)

#save gene names from genes_10 in a file
write.table(genes_10$GENE, file = paste0(wd, "/results/genes_10.txt"), row.names = FALSE, col.names = FALSE, quote = FALSE)

# plot
p <- ggplot(genes_10, aes(x = n_observations, y = n_variants)) +
  geom_point(size = 4, color = "steelblue") +
  geom_text(aes(label = GENE), vjust = -0.5, size = 2) +  # Tilføjer gen-navne som labels
  labs(
    title = "Number of Variants vs. Number of Observations per Gene",
    x = "Number of Observations",
    y = "Number of Unique Variants"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
p

#save as pdf
ggsave(paste0(wd, "/results/plots/genes_10_plot.pdf"), plot = p, width = 8, height = 6)
```
### plot variants per sample in seperate plots per population
```{r}

#replace underscores in population with spaces
gene_variants$METADATA <- gsub("_", " ", gene_variants$METADATA)

# create variant summary per population
variant_summary_pop <- gene_variants %>%
  group_by(GENE, METADATA) %>%
  summarise(
    n_variants = n_distinct(VARIANT),
    n_observations = n()
  ) %>%
  filter(n_observations > 1) %>%
  arrange(desc(n_variants))


# Get unique populations
populations <- unique(variant_summary_pop$METADATA)

# Define custom colors
custom_colors <- c(
  "Adult village population" = "#E74C3C",
  "Chimpanzee" = "#2E7F61",
  "Hadza population" = "#2E86C1",
  "School children population" = "#E67E22"
)

# Create PDF with one plot per population
pdf(paste0(wd, "/results/plots/variant_summary_per_population.pdf"), width=7, height=5)

for (pop in unique(variant_summary_pop$METADATA)) {
  pop_data <- variant_summary_pop[variant_summary_pop$METADATA == pop, ]
  
  p <- ggplot(pop_data, aes(x = n_observations, y = n_variants)) +
    geom_point(size = 4, color = custom_colors[pop]) +
    geom_text(aes(label = GENE), vjust = -0.5, size = 2) +
    labs(
      title = paste("Variants vs. Observations in", pop),
      x = "Number of Observations",
      y = "Number of Unique Variants"
    ) +
    ylim(0, 50) +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
  
  print(p)
}

dev.off()




```
